# -*- coding: utf-8 -*-
"""Copy of Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XV8MPrVRLAmAa7ibgF2ipWFie4Fz5eq
"""

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

data = pd.read_csv("/content/IRIS.csv")

# Select features for clustering (numerical features)
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
X = data[features]

# Scale the features (important for K-means)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Test different values of K
k_values = range(2, 11)  # Test K from 2 to 10
inertia_values = []

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=0)
    kmeans.fit(X_scaled)
    inertia_values.append(kmeans.inertia_)

# Evaluate performance (sum of squared distances to centroids)
plt.figure(figsize=(8, 6))
plt.plot(k_values, inertia_values, marker='o')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Sum of Squared Distances (Inertia)')
plt.title('K-means Performance vs. K')
plt.grid(True)
plt.show()

# Example with a chosen K (e.g., K=3)
k = 3  # Choose the best K based on the plot above
kmeans = KMeans(n_clusters=k, random_state=0)
kmeans.fit(X_scaled)

# Get cluster labels and centroids
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

# Evaluate performance (sum of squared distances)
inertia = kmeans.inertia_
print(f"Inertia (Sum of Squared Distances) for K={k}: {inertia}")

# Add cluster labels to the original DataFrame
data['cluster'] = labels

# Visualize the results (using the first two features for example)
plt.figure(figsize=(8, 6))
for cluster in range(k):
    cluster_data = data[data['cluster'] == cluster]
    plt.scatter(cluster_data['sepal_length'], cluster_data['sepal_width'], label=f'Cluster {cluster}')
plt.scatter(centroids[:, 0], centroids[:, 1], s=100, c='red', marker='X', label='Centroids')  # Plot centroids
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.title('K-means Clustering (K=3)')
plt.legend()
plt.grid(True)
plt.show()